@echo off
echo Menyalin assets ke folder public...

set SRC=C:\Users\farsya\projectcafemargin2\FOTO
set DEST=C:\Users\farsya\projectcafemargin2\cafemargin-app\frontend\public

if not exist "%DEST%\materi" mkdir "%DEST%\materi"

copy "%SRC%\Logo.jpeg" "%DEST%\logo.jpeg"
copy "%SRC%\Poster CafeMargin.png" "%DEST%\poster.png"

copy "%SRC%\CafeMargin Materi\1.png" "%DEST%\materi\1.png"
copy "%SRC%\CafeMargin Materi\2.png" "%DEST%\materi\2.png"
copy "%SRC%\CafeMargin Materi\3 (3).png" "%DEST%\materi\3.png"
copy "%SRC%\CafeMargin Materi\4 (2).png" "%DEST%\materi\4.png"
copy "%SRC%\CafeMargin Materi\5.png" "%DEST%\materi\5.png"
copy "%SRC%\CafeMargin Materi\6 (2).png" "%DEST%\materi\6.png"
copy "%SRC%\CafeMargin Materi\7 (2).png" "%DEST%\materi\7.png"
copy "%SRC%\CafeMargin Materi\8 (2).png" "%DEST%\materi\8.png"
copy "%SRC%\CafeMargin Materi\9 (2).png" "%DEST%\materi\9.png"
copy "%SRC%\CafeMargin Materi\10 (2).png" "%DEST%\materi\10.png"
copy "%SRC%\CafeMargin Materi\11 (2).png" "%DEST%\materi\11.png"
copy "%SRC%\CafeMargin Materi\12 (2).png" "%DEST%\materi\12.png"
copy "%SRC%\CafeMargin Materi\13.png" "%DEST%\materi\13.png"
copy "%SRC%\CafeMargin Materi\14.png" "%DEST%\materi\14.png"
copy "%SRC%\CafeMargin Materi\15.png" "%DEST%\materi\15.png"
copy "%SRC%\CafeMargin Materi\16.png" "%DEST%\materi\16.png"
copy "%SRC%\CafeMargin Materi\17.png" "%DEST%\materi\17.png"
copy "%SRC%\CafeMargin Materi\18.png" "%DEST%\materi\18.png"
copy "%SRC%\CafeMargin Materi\19.png" "%DEST%\materi\19.png"
copy "%SRC%\CafeMargin Materi\20.png" "%DEST%\materi\20.png"
copy "%SRC%\CafeMargin Materi\21.png" "%DEST%\materi\21.png"
copy "%SRC%\CafeMargin Materi\22.png" "%DEST%\materi\22.png"
copy "%SRC%\CafeMargin Materi\23.png" "%DEST%\materi\23.png"
copy "%SRC%\CafeMargin Materi\24.png" "%DEST%\materi\24.png"
copy "%SRC%\CafeMargin Materi\25.png" "%DEST%\materi\25.png"
copy "%SRC%\CafeMargin Materi\26.png" "%DEST%\materi\26.png"
copy "%SRC%\CafeMargin Materi\27.png" "%DEST%\materi\27.png"
copy "%SRC%\CafeMargin Materi\28.png" "%DEST%\materi\28.png"
copy "%SRC%\CafeMargin Materi\29.png" "%DEST%\materi\29.png"
copy "%SRC%\CafeMargin Materi\30.png" "%DEST%\materi\30.png"
copy "%SRC%\CafeMargin Materi\31.png" "%DEST%\materi\31.png"
copy "%SRC%\CafeMargin Materi\32.png" "%DEST%\materi\32.png"
copy "%SRC%\CafeMargin Materi\33.png" "%DEST%\materi\33.png"
copy "%SRC%\CafeMargin Materi\34.png" "%DEST%\materi\34.png"
copy "%SRC%\CafeMargin Materi\35.png" "%DEST%\materi\35.png"
copy "%SRC%\CafeMargin Materi\36.png" "%DEST%\materi\36.png"
copy "%SRC%\CafeMargin Materi\37.png" "%DEST%\materi\37.png"
copy "%SRC%\CafeMargin Materi\38.png" "%DEST%\materi\38.png"
copy "%SRC%\CafeMargin Materi\39.png" "%DEST%\materi\39.png"
copy "%SRC%\CafeMargin Materi\40.png" "%DEST%\materi\40.png"
copy "%SRC%\CafeMargin Materi\41.png" "%DEST%\materi\41.png"
copy "%SRC%\CafeMargin Materi\42.png" "%DEST%\materi\42.png"
copy "%SRC%\CafeMargin Materi\43.png" "%DEST%\materi\43.png"
copy "%SRC%\CafeMargin Materi\44.png" "%DEST%\materi\44.png"
copy "%SRC%\CafeMargin Materi\45.png" "%DEST%\materi\45.png"
copy "%SRC%\CafeMargin Materi\46.png" "%DEST%\materi\46.png"
copy "%SRC%\CafeMargin Materi\47.png" "%DEST%\materi\47.png"
copy "%SRC%\CafeMargin Materi\48.png" "%DEST%\materi\48.png"
copy "%SRC%\CafeMargin Materi\49.png" "%DEST%\materi\49.png"
copy "%SRC%\CafeMargin Materi\50.png" "%DEST%\materi\50.png"
copy "%SRC%\CafeMargin Materi\51.png" "%DEST%\materi\51.png"
copy "%SRC%\CafeMargin Materi\52.png" "%DEST%\materi\52.png"
copy "%SRC%\CafeMargin Materi\53.png" "%DEST%\materi\53.png"
copy "%SRC%\CafeMargin Materi\54.png" "%DEST%\materi\54.png"
copy "%SRC%\CafeMargin Materi\55.png" "%DEST%\materi\55.png"
copy "%SRC%\CafeMargin Materi\56.png" "%DEST%\materi\56.png"
copy "%SRC%\CafeMargin Materi\57.png" "%DEST%\materi\57.png"
copy "%SRC%\CafeMargin Materi\58.png" "%DEST%\materi\58.png"
copy "%SRC%\CafeMargin Materi\59.png" "%DEST%\materi\59.png"
copy "%SRC%\CafeMargin Materi\60.png" "%DEST%\materi\60.png"
copy "%SRC%\CafeMargin Materi\61.png" "%DEST%\materi\61.png"
copy "%SRC%\CafeMargin Materi\62.png" "%DEST%\materi\62.png"
copy "%SRC%\CafeMargin Materi\63.png" "%DEST%\materi\63.png"
copy "%SRC%\CafeMargin Materi\64.png" "%DEST%\materi\64.png"
copy "%SRC%\CafeMargin Materi\65.png" "%DEST%\materi\65.png"
copy "%SRC%\CafeMargin Materi\66.png" "%DEST%\materi\66.png"
copy "%SRC%\CafeMargin Materi\67.png" "%DEST%\materi\67.png"
copy "%SRC%\CafeMargin Materi\68.png" "%DEST%\materi\68.png"
copy "%SRC%\CafeMargin Materi\69.png" "%DEST%\materi\69.png"
copy "%SRC%\CafeMargin Materi\70.png" "%DEST%\materi\70.png"
copy "%SRC%\CafeMargin Materi\70B.png" "%DEST%\materi\70b.png"

echo.
echo Selesai! Semua assets sudah disalin ke public folder.
pause
